name: Luis A. Ortega
description: Probabilistic machine learning research by Luis A. Ortega.
url: https://ludvins.github.io
destination: ./_site
permalink: pretty

plugins:
  - jekyll-sitemap

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle
